config/routes.rb
Rails.application.routes.draw do
  root to: 'workers#index'
  resources :workers, only: [:new, :create, :update, :edit]
  resources :shifts, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :worker
  validates :date, uniqueness: true
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :shifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    @shifts = Shift.all
    @shifts_sorted = @shifts.sort_by {|h| h[:date]}
  end

  def new
    @shift = Shift.new
  end

  def create
    @shift = Shift.new(shift_params)
    if @shift.save
      redirect_to shifts_path
    else
      render "shifts/new"
    end
  end

  def edit
    @shift = Shift.find(params[:id])
  end

  def update
    @shift = Shift.find(params[:id])
    @shift.update(shift_params)
    redirect_to shifts_path
  end

  def shift_params
    params.require(:shift).permit(:date, :worker_id)
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def index
    @workers = Worker.all
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      redirect_to root_path
    else
      render "workers/new"
    end
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])
    @worker.update(worker_params)
    redirect_to root_path
  end

  private

  def worker_params
    params.require(:worker).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TEST CLAIRE GAUTIER</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body style="background-color:white;">
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-wagon-brand">
    <%= image_tag "logo.png"%>

  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to 'Workers', root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to 'Shifts', shifts_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">

    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to 'Workers', root_path %></li>
        <li><%= link_to 'Shifts', shifts_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shifts/_form.html.erb
<%= simple_form_for(@shift) do |f| %>
  <%= f.error_notification %>
  <%= f.input :date %>
  <%= f.association :worker%>
  <%= f.button :submit, "Submit", class: "btn btn-primary"  %>
<% end %>

app/views/shifts/edit.html.erb
<div class="container">
    <div class="row">
      <h2>Edit this shift</h2>
      <%= render 'form' %>
      <br>
      <%= link_to 'Back to all shifts', shifts_path, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/shifts/index.html.erb
<div class="container">
  <div class="row">
    <h3> <strong> SHIFTS </strong> </h3>
    <% @shifts_sorted.each do |shift| %>
      <div class="card">
        <p> <strong>Date</strong> <%= shift.date.strftime("%A, %B %e %Y") %>  </p>
        <p> <strong>On duty</strong> <%= shift.worker.name %> </p>
        <%= link_to "Edit this shift", edit_shift_path(shift) %>
      </div>
    <% end %>

    <div class="card">
      <%= link_to "Add a shift", new_shift_path, class: "btn btn-success" %>
      <br><br>
      <%= link_to "Back to all workers", root_path, class: "btn btn-danger" %>
    </div>

  </div>
</div>

app/views/shifts/new.html.erb
<div class="container">
    <div class="row">
      <h2>New shift</h2>
      <%= render 'form' %>
      <br>
      <%= link_to 'Back to all shifts', shifts_path, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/workers/_form.html.erb
<%= simple_form_for(@worker) do |f| %>
  <%= f.input :name, label: "Name", placeholder: "Claire Gautier" %>
  <%= f.button :submit, "Submit", class: "btn btn-primary"  %>
<% end %>

app/views/workers/edit.html.erb
<div class="container">
    <div class="row">
      <h2>Edit thi worker</h2>
      <%= render 'form' %>
      <br>
      <%= link_to 'Back', root_path, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/workers/index.html.erb
<div class="container">
  <div class="row">
    <h3> <strong> WORKERS LIST </strong></h3>
    <% @workers.each do |worker| %>
      <div class="card">
      <p> <%= worker.name %> </p>
      <%= link_to "Edit this worker", edit_worker_path(worker) %>
      </div>
    <% end %>

    <div class="card">
      <%= link_to "Add a worker", new_worker_path, class: "btn btn-success" %>
      <br> <br>
      <%= link_to "See shifts", shifts_path, class: "btn btn-warning" %>
    </div>
  </div>
</div>

app/views/workers/new.html.erb
<div class="container">
    <div class="row">
      <h2>New worker</h2>
      <%= render 'form' %>
      <br>
      <%= link_to 'Back', root_path, class: "btn btn-danger" %>
    </div>
  </div>
</div>